### PR TITLE
Beamer template

### PR DESCRIPTION
**Pull request by morevba**

### CODE REVIEW

**Comment by kbjarkefur** [comment]
Hi @prpaskov, @mrimal , @luizaandrade , @ramarty , @mcayala , @meyharmohd 

Thanks for helping to review the DIME Beamer Template that @morevba has prepared. While we can make updates to this in the future, it would be great if we make as much edits as possible before we start using this template. The template looks good to me, but the more eyes that look at it before we start using it the better.

Clone this repo and use [this file](https://github.com/worldbank/DIME-MSIE-Workshop/blob/8e6dbfba107dbb4d854abc91f7e254f2e01dc3a7/Beamer_template/Presentation_template.tex).

While you can test this however you want, there are two main things.

1. Do the slides look good from a design perspective? Is there anything you think could look bad in any situation? Try to think of situations slides are used. Small room, big room, printed, etc.
2. Try to break it. Try everything you usually do in a beamer presentation, and see if the template works as expected. Then try things you use less commonly but you use sometimes. Try to expose this template to as many situations as you can come up with as possible.

Even if you did not come up with any comments, please comment in this PR anyways. Good feedback is also feedback! 😄 

Thanks all!

**Comment by kbjarkefur** [comment]
@morevba , the logo files etc. are not in the repo. They are ignored in the `.gitignore` and I saw that you added a `!.png` but maybe the files were not added after that. Can you look into that? I can help tomorrow if you want.

**Comment by morevba** [comment]
@kbjarkefur I fixed the issue with png in the gitignore file and I added pdf to the list.

**Comment by luizaandrade** [comment]
I have looked at the design mostly and fixed some small things. I'd suggest trying to project this in case someone else has time. 

But I think it looks great!

**Comment by kbjarkefur** [comment]
Thanks @morevba ! I think this looks good! I really like the design. 

I have one question though. When you zoom in the font is pixelated. I have taken a zoomed in pic of another beamer template using _metropolis_ theme and this one. See the difference in the pictures below.

I do not know how to solve this from the top of my mind, and you - @morevba - have already spent a lot of time on this template, so unless you want to, don't feel pressured that you have to spend another few days solving this. Anyone else that I have suggestion for why this happens and how it can be solved?

-- EDIT : Sorry if this is a bit petty, but this is a template we will use so many times, that I think it is worth working out all details --

Another beamer presentation:
image

This beamer teamplate:
image

**Comment by morevba** [comment]
@kbjarkefur Thanks for spotting the font issue. I realized what was causing the fonts to be pixelated and it was the \usepackage[T1]{fontenc} which allows for accented characters so an 'ö' is an actual single glyph in the font. But I dont think we will be dealing accented characters in any presentations unless it deals with someone's name. I removed the package and the font looks cleaner now

**Comment by prpaskov** [comment]
Looks great! The code didn't run for me because of the images, so I commented those lines out and saw the presentation without logos, etc. It might be nice to add code for more features (i.e. subtitles) and "specialized" pages (i.e. code example pages, a bibliography) to ensure that those aspects remain uniform between presentations if/when people use them. Maybe these details are too granular for the moment...but if this seems useful, I'm happy to do it on Monday.

**Comment by morevba** [comment]
Thanks @prpaskov for the feedback. I was just thinking about the need to add more specialized slides that show Stata codes, graphs, and tables. I added a slide that has Stata code and text side by side. In terms of adding other specialized slides, I was waiting until we start converting all the current session presentations in PPT to Beamer.  Because of a lot of them already have tables and graphs and then we can test out how well this template holds up. 

I can also look for session presentations from last year that has both graphs and tables and then converting them to see how graphs and tables look with the new table.

**Pull request merged**
